baseURL = "https://scarpet.pages.dev/"
languageCode = "en-us"
title = "Scarpet"

pluralizeListTitles = false

[params]
repository = "https://github.com/FedericoCarboni/scarpet-docs"

[markup]
[markup.highlight]
# Chroma does not support Scarpet and Hugo does not allow custom lexers so
# highlighting is handled by JavaScript using PrismJS (see assets/js/scarpet.js)
codeFences = false

[outputFormats]
[outputFormats.DocData]
mediaType = "application/json"
baseName = "docdata"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "JSON", "DocData"]
